#%RAML 1.0
title: leCalendar
version: v1
baseUri: http://api.samplehost.com
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
/helloWorld:
  get:
    description: Acest get va putea identifica numele de utilizator al unui administrator cu scopul de a permite unui utilizator contactarea unei persoane care poate oferi informatii sau ajutor tehnic;
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "name" : "admin_contact_name"
                "date" : "18.04.2019"
                "last_login" : "18.08.2017"
                "contactable" : "no"
              }

 post:
   description: Permite crearea unui eveniment nou in calendar
        responses:
     200:
       body:
         application/json:
           example: |
             {
                "date" : "18.04.2019"
                "month": "aprilie"
                "day" : "joi"
                "eveniment" :"plecare Bucuresti"
              }




 put:
   description: Permite actualizarea unor intrari deja existente in calendar in cazul in care utlizatorul doreste sa schimbe informatii in cadrul unui event;
   responses:
     200:
       body:
         application/json:
           example: |
             {
                "date" : "18.04.2019"
                "month": "aprilie"
                "day" : "joi"
                "eveniment" :"plecare Moldova"
              }
